$(document).ready(function(){
	// $.ajax({
	// 	url:'./js/mock-injuries.json',
	// 	dataType:'json',
	// 	success:function(data){
	// 		console.log("TEST");
	// 		console.log(data);
	// 	}
	// });

	var data = [
		{
			"week": "week-1", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-2", 
			"teams":[
				{"name":"New York Giants","injuries":9},
				{"name":"Dallas Cowboys","injuries":10},
				{"name":"Washington Redskins","injuries":9},
				{"name":"Philadelphia Eagles","injuries":5},
				{"name":"Green Bay Packers","injuries":5},			
				{"name":"Minnesota Vikings","injuries":10},
				{"name":"Detroit Lions","injuries":6},
				{"name":"Chicago Bears","injuries":8},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":6},
				{"name":"New Orleans Saints","injuries":5},
				{"name":"Tampa Bay Buccaneers","injuries":10},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":4},	
				{"name":"San Francisco 49ers","injuries":6},
				{"name":"St. Louis Rams","injuries":5},	
				{"name":"New England Patriots","injuries":6},
				{"name":"New York Jets","injuries":6},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":13},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":16},
				{"name":"Cleveland Browns","injuries":8},
				{"name":"Cincinatti Bengals","injuries":16},	
				{"name":"Houston Texans","injuries":19},
				{"name":"Tenessee Titans","injuries":6},
				{"name":"Indianapolis Colts","injuries":9},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":6},
				{"name":"Kansas City Chiefs","injuries":12},
			
			]
		},
	{
			"week": "week-3", 
			"teams":[
				{"name":"New York Giants","injuries":7},
				{"name":"Dallas Cowboys","injuries":12},
				{"name":"Washington Redskins","injuries":13},
				{"name":"Philadelphia Eagles","injuries":12},
				{"name":"Green Bay Packers","injuries":5},			
				{"name":"Minnesota Vikings","injuries":9},
				{"name":"Detroit Lions","injuries":10},
				{"name":"Chicago Bears","injuries":11},
				{"name":"Atlanta Falcons","injuries":4},
				{"name":"Carolina Panthers","injuries":14},
				{"name":"New Orleans Saints","injuries":9},
				{"name":"Tampa Bay Buccaneers","injuries":12},
				{"name":"Arizona Cardinals","injuries":11},
				{"name":"Seattle Seahawks","injuries":9},	
				{"name":"San Francisco 49ers","injuries":9},
				{"name":"St. Louis Rams","injuries":8},	
				{"name":"New England Patriots","injuries":11},
				{"name":"New York Jets","injuries":9},	
				{"name":"Buffalo Bills","injuries":8},
				{"name":"Miami Dolphins","injuries":17},
				{"name":"Baltimore Ravens","injuries":6},	
				{"name":"Pittsburgh Steelers","injuries":8},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":13},	
				{"name":"Houston Texans","injuries":14},
				{"name":"Tenessee Titans","injuries":4},
				{"name":"Indianapolis Colts","injuries":15},	
				{"name":"Jacksonville Jaguars","injuries":16},
				{"name":"San Diego Chargers","injuries":12},
	   			{"name":"Denver Broncos","injuries":10},	
				{"name":"Oakland Raiders","injuries":9},
				{"name":"Kansas City Chiefs","injuries":12},
			
			]
		},
	{
			"week": "week-4", 
			"teams":[
				{"name":"New York Giants","injuries":7},
				{"name":"Dallas Cowboys","injuries":9},
				{"name":"Washington Redskins","injuries":17},
				{"name":"Philadelphia Eagles","injuries":12},
				{"name":"Green Bay Packers","injuries":6},			
				{"name":"Minnesota Vikings","injuries":9},
				{"name":"Detroit Lions","injuries":13},
				{"name":"Chicago Bears","injuries":11},
				{"name":"Atlanta Falcons","injuries":5},
				{"name":"Carolina Panthers","injuries":8},
				{"name":"New Orleans Saints","injuries":8},
				{"name":"Tampa Bay Buccaneers","injuries":9},
				{"name":"Arizona Cardinals","injuries":0},
				{"name":"Seattle Seahawks","injuries":0},	
				{"name":"San Francisco 49ers","injuries":10},
				{"name":"St. Louis Rams","injuries":0},	
				{"name":"New England Patriots","injuries":7},
				{"name":"New York Jets","injuries":8},	
				{"name":"Buffalo Bills","injuries":11},
				{"name":"Miami Dolphins","injuries":23},
				{"name":"Baltimore Ravens","injuries":8},	
				{"name":"Pittsburgh Steelers","injuries":9},
				{"name":"Cleveland Browns","injuries":0},
				{"name":"Cincinatti Bengals","injuries":0},	
				{"name":"Houston Texans","injuries":13},
				{"name":"Tenessee Titans","injuries":5},
				{"name":"Indianapolis Colts","injuries":17},	
				{"name":"Jacksonville Jaguars","injuries":12},
				{"name":"San Diego Chargers","injuries":13},
	   			{"name":"Denver Broncos","injuries":0},	
				{"name":"Oakland Raiders","injuries":9},
				{"name":"Kansas City Chiefs","injuries":7},
			
			]
		},
	{
			"week": "week-5", 
			"teams":[
				{"name":"New York Giants","injuries":4},
				{"name":"Dallas Cowboys","injuries":6},
				{"name":"Washington Redskins","injuries":14},
				{"name":"Philadelphia Eagles","injuries":11},
				{"name":"Green Bay Packers","injuries":7},			
				{"name":"Minnesota Vikings","injuries":10},
				{"name":"Detroit Lions","injuries":11},
				{"name":"Chicago Bears","injuries":12},
				{"name":"Atlanta Falcons","injuries":6},
				{"name":"Carolina Panthers","injuries":10},
				{"name":"New Orleans Saints","injuries":11},
				{"name":"Tampa Bay Buccaneers","injuries":10},
				{"name":"Arizona Cardinals","injuries":9},
				{"name":"Seattle Seahawks","injuries":6},	
				{"name":"San Francisco 49ers","injuries":13},
				{"name":"St. Louis Rams","injuries":5},	
				{"name":"New England Patriots","injuries":8},
				{"name":"New York Jets","injuries":9},	
				{"name":"Buffalo Bills","injuries":8},
				{"name":"Miami Dolphins","injuries":0},
				{"name":"Baltimore Ravens","injuries":9},	
				{"name":"Pittsburgh Steelers","injuries":12},
				{"name":"Cleveland Browns","injuries":7},
				{"name":"Cincinatti Bengals","injuries":14},	
				{"name":"Houston Texans","injuries":17},
				{"name":"Tenessee Titans","injuries":6},
				{"name":"Indianapolis Colts","injuries":10},	
				{"name":"Jacksonville Jaguars","injuries":11},
				{"name":"San Diego Chargers","injuries":15},
	   			{"name":"Denver Broncos","injuries":7},	
				{"name":"Oakland Raiders","injuries":0},
				{"name":"Kansas City Chiefs","injuries":9},
			
			]
		},
	{
			"week": "week-6",
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-7",
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-8", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-9",
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-10", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-11", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-12", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-13", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-14",
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-15", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-16",
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		},
	{
			"week": "week-17", 
			"teams":[
				{"name":"New York Giants","injuries":6},
				{"name":"Dallas Cowboys","injuries":7},
				{"name":"Washington Redskins","injuries":4},
				{"name":"Philadelphia Eagles","injuries":6},
				{"name":"Green Bay Packers","injuries":4},			
				{"name":"Minnesota Vikings","injuries":7},
				{"name":"Detroit Lions","injuries":3},
				{"name":"Chicago Bears","injuries":4},
				{"name":"Atlanta Falcons","injuries":2},
				{"name":"Carolina Panthers","injuries":1},
				{"name":"New Orleans Saints","injuries":3},
				{"name":"Tampa Bay Buccaneers","injuries":8},
				{"name":"Arizona Cardinals","injuries":8},
				{"name":"Seattle Seahawks","injuries":8},	
				{"name":"San Francisco 49ers","injuries":5},
				{"name":"St. Louis Rams","injuries":7},	
				{"name":"New England Patriots","injuries":5},
				{"name":"New York Jets","injuries":5},	
				{"name":"Buffalo Bills","injuries":7},
				{"name":"Miami Dolphins","injuries":12},
				{"name":"Baltimore Ravens","injuries":2},	
				{"name":"Pittsburgh Steelers","injuries":7},
				{"name":"Cleveland Browns","injuries":9},
				{"name":"Cincinatti Bengals","injuries":12},	
				{"name":"Houston Texans","injuries":6},
				{"name":"Tenessee Titans","injuries":3},
				{"name":"Indianapolis Colts","injuries":8},	
				{"name":"Jacksonville Jaguars","injuries":13},
				{"name":"San Diego Chargers","injuries":9},
	   			{"name":"Denver Broncos","injuries":9},	
				{"name":"Oakland Raiders","injuries":8},
				{"name":"Kansas City Chiefs","injuries":13},
			
			]
		}

	]

	putDataOnPage();
	manageDropDown();

	function putDataOnPage(){
		//loop through data and add injury lists to page, then hide'
		// $('.week-box').hide();
			$.each(data,function(index,week){//code goes here
				// console.log(week);
				// console.log(week.week); // week id 
				// console.log(week.teams); //array of teams and injuries to loop through
				var weekNum = index + 1;
				var weekBox = '<div class="week-box" id="week-'+weekNum+'"><h2>'+week.week+'</h2><ul></ul></div>';
				$('#weeks').append(weekBox);

				console.log(week.teams);
				$.each(week.teams,function(index,team){
					var listItem = "<li>"+team.name+": "+team.injuries+"</li>";
					console.log(listItem);
					$('#week-'+weekNum+' ul').append(listItem);
				});

			});
	
			$('.week-box').hide();
	}

	function manageDropDown(){

		$('#week-list').change(function(){
			var weeklist = document.getElementById('week-list');
			var selectedWeek = weeklist.options[weeklist.selectedIndex].value;
			console.log(selectedWeek);
		$.each($('.week-box'),function(index,weekBox){
			$(weekBox).slideUp();
		}); 
		$('#'+ selectedWeek).slideDown();

		});
		//grab the value of the drop down item selected
		//loop through data and match that value to the corresponding week in your data
		//show selected week
	}

	console.log(data);
	
}); 